Add secondary_index check
This was removed with bcdac6b7a3b3474d6ff6b51c23af2689ae66455d but
breaks fresh gerrit installs.  $secondary_index is set true in
system-config: modules/openstack_project/manifests/gerrit.pp and
without it, gerrit refuses to start saying

  com.google.inject.ProvisionException: Unable to provision, see the following errors:

  1) No index versions ready; run Reindex

After running the reindex manually, "/etc/init.d/gerrit start" then
works.

Add back the secondary_index check

Change-Id: I98ce9ff87570a86e9b58b38d0605313ee5ee2758